---
title: "Plot NEON LiDAR Data"
author: "Megan A. Jones"
date: "May 23, 2016"
output: html_document
---

This script creates plots from raster LiDAR data collected over NEON's Lower 
Teakettle field site. 

```{r set-up, echo=FALSE, warning=FALSE} 
# load needed packages
library(rgdal)
library(raster)

# set working directory to ensure R can find the file we wish to import
setwd("~/Documents/data/NEONDI-2016/")

```

Loading the DSM GeoTIFF for Lower Teakettle

```{r load-dsm-raster}
# import dsm
teak_dsm <- raster("NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarDSM.tif")
```

Plot the DSM and add a title

``` {r plot-raster}
# plot raster object
plot(teak_dsm, main="Digital Surface Model\nNEON Lower Teakettle Field Site")
```

Load and plot TEAK CHM. 

```{r load-plot-chm}
# load data
teak_chm <- raster("NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarCHM.tif")

# plot raster
plot(teak_chm, main="Canopy Height Model\nNEON Lower Teakettle Field Site")
```

Create a histogram of both the DSM and CHM

```{r plot-hist}
# Histogram of TEAK DSM
hist(teak_dsm)

# Histogram of TEAK CHM
hist(teak_chm)
